name: Lint and Build on Pull Request

on:
    pull_request:
        branches:
            - main

jobs:
    lint-and-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: corepack enable

            - uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            - run: npm install

            - name: Lint Code
              run: npm run lint

            - name: Build Nuxt App
              run: npx nuxt build
